#!/usr/bin/env node
/**
 * Fetch /api/arena/manifest from a running backend and emit
 * src/types.generated.ts with the symbol enum, action enum, and
 * rejection-reason enum derived from the live schema. Run before
 * publishing a new runtime version so users get types that match what
 * the server actually accepts.
 *
 * Usage:
 *   npm run codegen
 *   npm run codegen -- --url https://staging.hermesarena.live
 */
import fs from 'fs';
import path from 'path';
import fetch from 'node-fetch';
import { manifest as fetchManifest } from '../src/client';

interface ManifestSchemas {
  Decision?: { properties?: { symbol?: { enum?: string[] }; action?: { enum?: string[] } } };
  Rejection?: { properties?: { reason?: { enum?: string[] } } };
}

interface Manifest {
  schemas?: ManifestSchemas;
  rules?: { maxDecisionsPerCycle?: number; reasonMaxChars?: number; maxPositionSizePercent?: number };
  sdk?: { headerName?: string };
}

const DEFAULT_URL = process.env.YETI_ARENA_URL || 'http://127.0.0.1:3001';

function parseArgs(argv: string[]): { url: string } {
  let url = DEFAULT_URL;
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === '--url' && argv[i + 1]) url = argv[++i];
  }
  return { url };
}

function asUnion(values: string[] | undefined, fallback: string): string {
  if (!values || values.length === 0) return fallback;
  return values.map((v) => JSON.stringify(v)).join(' | ');
}

async function main(): Promise<void> {
  const { url } = parseArgs(process.argv);
  process.stdout.write(`Fetching manifest from ${url} ... `);
  const m = (await fetchManifest(url)) as Manifest;
  process.stdout.write('ok\n');

  const symbolEnum = m.schemas?.Decision?.properties?.symbol?.enum;
  const actionEnum = m.schemas?.Decision?.properties?.action?.enum;
  const rejectionEnum = m.schemas?.Rejection?.properties?.reason?.enum;

  if (!symbolEnum || !actionEnum || !rejectionEnum) {
    throw new Error(
      'Manifest is missing schemas.{Decision.properties.symbol.enum, Decision.properties.action.enum, Rejection.properties.reason.enum}. ' +
      'Backend may be older than the schema-publishing version.',
    );
  }

  const body = `// Auto-generated by scripts/codegen.ts — do not edit by hand.
// Regenerate with: npm run codegen
// Source: ${url}/api/arena/manifest
// Generated: ${new Date().toISOString()}

export type GeneratedSymbol = ${asUnion(symbolEnum, 'string')};
export type GeneratedAction = ${asUnion(actionEnum, '"LONG" | "SHORT" | "FLAT"')};
export type GeneratedRejectionReason = ${asUnion(rejectionEnum, 'string')};

export const SUPPORTED_SYMBOLS: readonly GeneratedSymbol[] = ${JSON.stringify(symbolEnum)} as const;
export const SUPPORTED_ACTIONS: readonly GeneratedAction[] = ${JSON.stringify(actionEnum)} as const;
export const REJECTION_REASONS: readonly GeneratedRejectionReason[] = ${JSON.stringify(rejectionEnum)} as const;

export const RULES = ${JSON.stringify(m.rules ?? {}, null, 2)} as const;
`;

  const outPath = path.join(__dirname, '..', 'src', 'types.generated.ts');
  fs.writeFileSync(outPath, body);
  process.stdout.write(`Wrote ${path.relative(process.cwd(), outPath)}\n`);
  process.stdout.write(`  symbols: ${symbolEnum.length}, actions: ${actionEnum.length}, rejections: ${rejectionEnum.length}\n`);
}

main().catch((err) => {
  process.stderr.write(`codegen failed: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
